### ISSUE TITLE
Add dockerfile

### ISSUE THREAD

**Issue by andre2007** [denizzzka/d_c_arm_test#18]
By adding a Dockerfile with the needed installation steps and the meson build command as Entrypoint it becomes quite easy to use your repository (operation system independent).

The users just have to clone your repository and execute docker build & docker run with the source code folder mounted. The compiled artifact is written back to the mounted folder and therefore available on the host file system after the docker run.

Maybe you also profit from the Dockerfile as you can maybe run the Dockerfile from github Actions (e.g. as pull request voter) and therefore have checks.

Another advantage is, the installation steps are described exactly and  reusable in contrast to the prosa text of the README.md.

**Comment by denizzzka** [comment]
I do not mind. I can’t do it myself - I don't possess Docker knowledge sufficiently.

**Comment by andre2007** [comment]
While I have some docker knowledge I have no knowledge regarding meson / freertos... I will try to get it running and create a PR in case I succeed.

Which linux operation system can I use as base system (which one do you used)? ubuntu focal, debian 10, alpine...

**Comment by denizzzka** [comment]
I build this on Debian.

If something won't compile feel free to ask me. There can be something hard-coded or issues like this. This is usually happens when the package is used by a too few people.

**Comment by andre2007** [comment]
I made some progress, this is the Dockerfile I came up so far.

``` Dockerfile
FROM debian:bullseye

RUN apt-get update && apt-get upgrade -y \
    && apt-get install --no-install-recommends -y build-essential clang libclang-11-dev gcc-arm-none-eabi \
       dub ldc git lld llvm ninja-build python3 python3-pip python3-setuptools python3-wheel

# Install meson
ENV PATH=$PATH:/root/.local/bin
RUN pip3 install --user meson

# Compile
COPY . /tmp/project
RUN cd /tmp/project \
    && meson setup --cross-file arm_cortex_m4_cross.ini -Doptimization=s -Ddebug=true /tmp/project/build \
    && cd /tmp/project/build \
    && ninja
```

The build fails with error:
> d/meson.build:78:0: ERROR: File freertos_druntime_backend/external/core/gc.d does not exist.

This file is missing here:
https://github.com/denizzzka/d_c_arm_test/tree/master/d/freertos_druntime_backend/external/core

How can I fix this issue?

**Comment by denizzzka** [comment]
Oops, sorry! I just forgot to add local d/freertos_druntime_backend/external/core/gc.d to repository
Fixed in current ~master

Also, found similar error after fix previous. I'll fix it in short time.

**Comment by denizzzka** [comment]
@andre2007 done, please try again!

**Comment by andre2007** [comment]
I rebased to master and tried again. In the dockerfile I made a small adaption. In my case dpp needs to know where to find llvm, therefore I set the environment variable DFLAGS. Maybe this could be set in a meson config file specifically for dpp, but I do not have any meson knowledge.

``` Dockerfile
FROM debian:bullseye

RUN apt-get update && apt-get upgrade -y \
    && apt-get install --no-install-recommends -y build-essential clang libclang-11-dev gcc-arm-none-eabi \
       dub ldc git lld llvm ninja-build python3 python3-pip python3-setuptools python3-wheel

# Install meson
ENV PATH=$PATH:/root/.local/bin
RUN pip3 install --user meson

# Compile
ENV DFLAGS="-L=-L/usr/lib/llvm-11/lib/"
COPY . /tmp/project
RUN cd /tmp/project \
    && meson setup --cross-file arm_cortex_m4_cross.ini -Doptimization=s -Ddebug=true /tmp/project/build \
    && cd /tmp/project/build \
    && ninja
```

First error, unknown OS:
>[1063/1100] Compiling D object firmware.elf.p/d_source_arm_cortex_debug.d.o
FAILED: firmware.elf.p/d_source_arm_cortex_debug.d.o
ldc2 -I=firmware.elf.p -I=. -I=.. -I=../d/source -I=../d/source/bindings -I=../d/freertos_dpp_bindings -I=../d/freertos_druntime_backend -I=../subprojects/libopencm3/include -I=subprojects/picolibc/newlib/libc/machine/arm -I=../subprojects/picolibc/newlib/libc/machine/arm -I=subprojects/picolibc/newlib/libc/tinystdio -I=../subprojects/picolibc/newlib/libc/tinystdio -I=subprojects/picolibc -I=../subprojects/picolibc -I=subprojects/picolibc/newlib/libc/include -I=../subprojects/picolibc/newlib/libc/include -I=../subprojects/libunwind/include -I=../subprojects/libunwind/include/mach-o -I=../subprojects/libunwind/src -enable-color -wi -Os -g -d-debug '' --boundscheck=off --d-version=DruntimeAbstractRt --d-version=CRuntime_Abstract --d-version=AsmExternal --d-version=GENERIC_IO --mtriple=thumbv7em-unknown-none-eabi --fthread-model=local-exec -Oz -of=firmware.elf.p/d_source_arm_cortex_debug.d.o -c ../d/source/arm_cortex_debug.d
/usr/lib/ldc/x86_64-linux-gnu/include/d/std/system.d(58): Error: static assert:  "Unknown OS."

Second error, undefined identifier time_t:
>FAILED: firmware.elf.p/d_source_drivers_max7219.d.o
ldc2 -I=firmware.elf.p -I=. -I=.. -I=../d/source -I=../d/source/bindings -I=../d/freertos_dpp_bindings -I=../d/freertos_druntime_backend -I=../subprojects/libopencm3/include -I=subprojects/picolibc/newlib/libc/machine/arm -I=../subprojects/picolibc/newlib/libc/machine/arm -I=subprojects/picolibc/newlib/libc/tinystdio -I=../subprojects/picolibc/newlib/libc/tinystdio -I=subprojects/picolibc -I=../subprojects/picolibc -I=subprojects/picolibc/newlib/libc/include -I=../subprojects/picolibc/newlib/libc/include -I=../subprojects/libunwind/include -I=../subprojects/libunwind/include/mach-o -I=../subprojects/libunwind/src -enable-color -wi -Os -g -d-debug '' --boundscheck=off --d-version=DruntimeAbstractRt --d-version=CRuntime_Abstract --d-version=AsmExternal --d-version=GENERIC_IO --mtriple=thumbv7em-unknown-none-eabi --fthread-model=local-exec -Oz -of=firmware.elf.p/d_source_drivers_max7219.d.o -c ../d/source/drivers/max7219.d
/usr/lib/ldc/x86_64-linux-gnu/include/d/core/stdc/time.d(33): Error: undefined identifier time_t, did you mean function time?

Third error, maybe caused by error 1 & 2:
>llvm-ar: .dub/obj/clang.o: No such file or directory.
Error: llvm-ar failed with status: 1
/usr/bin/ldc2 failed with exit code 1.

Complete log also attached
[log.txt](https://github.com/denizzzka/d_c_arm_test/files/5863148/log.txt)

**Comment by denizzzka** [comment]
> First error, unknown OS:
>> /usr/lib/ldc/x86_64-linux-gnu/include/d/std/system.d(58): Error: static assert: "Unknown OS."

I forgot what I patched my system installation of Phobos by this way:
```D
    /// The OS that the program was compiled for.
    version (Win32)        OS os = OS.win32;
    else version (Win64)   OS os = OS.win64;
    else version (Android) OS os = OS.android;
    else version (linux)   OS os = OS.linux;
    else version (OSX)     OS os = OS.osx;
    else version (iOS)     OS os = OS.iOS;
    else version (tvOS)    OS os = OS.tvOS;
    else version (watchOS) OS os = OS.watchOS;
    else version (FreeBSD) OS os = OS.freeBSD;
    else version (NetBSD)  OS os = OS.netBSD;
    else version (DragonFlyBSD) OS os = OS.dragonFlyBSD;
    else version (Posix)   OS os = OS.otherPosix;
    else OS os = OS.otherNonPosix;
    //~ else static assert(0, "Unknown OS.");
```

I hesitated to suggest any solution patch for this to the master Phobos branch.

> Second error, undefined identifier time_t:
>> /usr/lib/ldc/x86_64-linux-gnu/include/d/core/stdc/time.d(33): Error: undefined identifier time_t, did you mean function time?

Forgotten dirty patch again: weeks ago I just replaced core directory of system druntime installation by soft link to my non_posix branch of druntime:
```
$ ls -ld /usr/lib/ldc/x86_64-linux-gnu/include/d/core                                                                                                               Пн 25 янв 2021 18:08:22
lrwxrwxrwx 1 denizzz denizzz 35 Oct 20 19:01 /usr/lib/ldc/x86_64-linux-gnu/include/d/core -> /home/denizzz/Dev/druntime/src/core
```

It works well for default builds and for embedded builds too, so I just forgot about it.

**Comment by denizzzka** [comment]
@andre2007 do not worry - number of problems like such is small, only a ~couple more will come across. But it is useful to pass across build on a fresh system for document and/or solve this issues.

**Comment by andre2007** [comment]
With this dockerfile the whole process is working. It can just be executed using command `docker build`. The elf file can then be copied from a running docker container to the host system.

> In an ideal scenario you would build the docker image once (takes longer), here everything except the actual
application (app.d) is build.
The actual app would then be build using command `docker run` which would be super fast, as it only compiles `app.d`.
But here I lack meson knowledge and I assume, the project structure of your repository would need to be changed.
Therefore I would keep it as it is.


``` Dockerfile
FROM debian:bullseye

RUN apt-get update && apt-get upgrade -y \
    && apt-get install --no-install-recommends -y build-essential clang libclang-11-dev gcc-arm-none-eabi \
       dub ldc git lld llvm ninja-build python3 python3-pip python3-setuptools python3-wheel

# Install meson
ENV PATH=$PATH:/root/.local/bin
RUN pip3 install --user meson

# Patch phobos for FreeRTOS
RUN sed -i 's/else static assert(0, "Unknown OS.");/else OS os = OS.otherNonPosix;/g' /usr/lib/ldc/x86_64-linux-gnu/include/d/std/system.d \
	&& sed -i 's/otherPosix /otherPosix, otherNonPosix /g' /usr/lib/ldc/x86_64-linux-gnu/include/d/std/system.d

# Patch ldc druntime
RUN cd /tmp && git clone https://github.com/denizzzka/druntime \
    && cd /usr/lib/ldc/x86_64-linux-gnu/include/d/ && rm -r core \
	&& ln -s /tmp/druntime/src/core/ core
	
# Compile
ENV DFLAGS="-L=-L/usr/lib/llvm-11/lib/"
COPY . /tmp/project
RUN cd /tmp/project \
    && meson setup --cross-file arm_cortex_m4_cross.ini -Doptimization=s -Ddebug=true /tmp/project/build \
    && cd /tmp/project/build \
    && ninja
```

One question, from raspberry there is a new device called `Raspberry Pi Pico`. Is this somehow supported by your repository?

**Comment by denizzzka** [comment]
> One question, from raspberry there is a new device called Raspberry Pi Pico. Is this somehow supported by your repository?

I tested this repository only on stm32 chips with ARM Cortex M3 and M4, but maybe it will work.

**Comment by andre2007** [comment]
> I forgot what I patched my system installation of Phobos by this way:

Is my understanding correct that phobos/dmd needs to know FreeRTOS? 
I would create an issue for dmd/phobos

**Comment by denizzzka** [comment]
> Is my understanding correct that phobos/dmd needs to know FreeRTOS?

No. Only druntime needs to know about "how to create thread". FreeRTOS (or another MCU OS) is simpliest way to provide this functionality on single core MCUs.

**Comment by andre2007** [comment]
I wondered how an official PR for Phobos would look like to make the patch in your repository superfluous. 
I assumed a constant "otherNonPosix" would not be accepted as it is too nonspecific. But what would be the new constant if not "freertos"?
In case it is freertos, a version "freertos" would also be needed...

**Comment by denizzzka** [comment]
I think ExternalOS or OtherOS must be added into official compiler versions, not just into Phobos enum.

> In case it is freertos, a version "freertos" would also be needed...

No, this is not FreeRTOS strictly, this is something like "FreeRTOS+external_backend OS". Thus, we can't enumerate all possible combinations of MCU OSes or schedulers amd backends.

**Comment by andre2007** [comment]
PR https://github.com/denizzzka/d_c_arm_test/pull/19

**Comment by denizzzka** [comment]
Merged
